# Stage 1: Build the React app
FROM node:18-alpine AS build
WORKDIR /usr/src/app
COPY packages/client/package*.json ./
RUN npm install
COPY packages/client ./
RUN npm run build

# Stage 2: Serve the app with Nginx
FROM nginx:stable-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
